---

- name: 'CONFIG | Create statsd configuration file'
  template:
    src: "{{ role_path }}/templates/config.js.j2"
    dest: "{{ statsd_paths.files.main_config.path }}"
    owner: "{{ statsd_paths.files.main_config.owner | default(statsd_user.name) }}"
    group: "{{ statsd_paths.files.main_config.group | default(statsd_group.name) }}"
    mode: "{{ statsd_paths.files.main_config.mode | default('0400') }}"
  notify:
    - 'HANDLER | Restart statsd'
