---

- name: 'Create statsd configuration file'
  become: True
  template:
    src: 'config.js.j2'
    dest: "{{ statsd_config_file }}"
    owner: "{{ statsd_user_name }}"
    group: "{{ statsd_group_name }}"
    mode: "{{ statsd_config_mode }}"
  notify:
    - 'Restart statsd'
