---

# Debian family specific installation tasks

- name: 'INSTALL | APT | Install system prerequisites'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: "{{ statsd_repository_update_cache }}"
    cache_valid_time: "{{ statsd_repository_cache_valid_time }}"
  with_items: "{{ statsd_prerequisites_packages }}"
  when: (ansible_distribution_release == "jessie" or ansible_distribution == "Ubuntu")

- name: 'INSTALL | APT | https method'
  apt:
    name: '{{ nodejs_prerequisites_packages_stretch }}'
    state: 'present'
    update_cache: "{{ statsd_repository_update_cache }}"
    cache_valid_time: "{{ statsd_repository_cache_valid_time }}"
  when: (ansible_distribution_release == "stretch")

- name: 'ADD | APT | Key nodeJS respository'
  apt_key:
    url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    state: 'present'
  when: (ansible_distribution_release == "stretch")

- name: 'ADD | APT | nodeJS repository'
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_4.x stretch main'
    state: 'present'
  when: (ansible_distribution_release == "stretch")

- name: 'INSTALL | APT | Install system prerequisites 4 Stretch'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: "{{ statsd_repository_update_cache }}"
    cache_valid_time: "{{ statsd_repository_cache_valid_time }}"
  with_items: "{{ statsd_prerequisites_packages_stretch }}"
  when: (ansible_distribution_release == "stretch")
