---

- name: 'Install system prerequisites'
  become: True
  apt:
    name: "{{ item }}"
    state: "{{ statsd_prerequisites_state }}"
    update_cache: True
    cache_valid_time: "{{ statsd_prerequisites_cache_valid_time }}"
  with_items: "{{ statsd_prerequisites_packages }}"
  when: "{{ (ansible_os_family | lower) == 'debian' }}"


- name: 'Create statsd user'
  become: True
  user:
    name: "{{ statsd_user_name }}"
    shell: "{{ statsd_user_shell }}"
    home: "{{ statsd_user_home }}"
    createhome: "{{ statsd_user_create_home }}"
    state: 'present'


- name: 'Download statsd from git repository'
  become: True
  git:
    repo: "{{ statsd_git_repository_url }}"
    dest: "{{ statsd_git_dest_folder }}"
    bare: "{{ statsd_git_option_bare }}"
    clone: "{{ statsd_git_option_clone }}"
    force: "{{ statsd_git_option_force }}"
    update: "{{ statsd_git_option_update }}"
    version: "{{ statsd_version }}"
  notify:
    - 'Restart statsd'


- name: 'Install statsd NodeJS dependencies'
  become: True
  npm:
    global: "{{ statsd_npm_option_global }}"
    path: "{{ statsd_npm_option_path }}"
    production: "{{ statsd_npm_option_production }}"
  notify:
    - 'Restart statsd'


- name: 'Install statsd init.d script'
  become: True
  template:
    src: 'init.j2'
    dest: "{{ statsd_init_file }}"
    owner: "{{ statsd_user_name }}"
    group: "{{ statsd_group_name }}"
    mode: "{{ statsd_init_mode }}"
  notify:
    - 'Restart statsd'


- name: 'Manage statsd folders'
  become: True
  file:
    path: "{{ item }}"
    state: 'directory'
    owner: "{{ statsd_user_name }}"
    group: "{{ statsd_group_name }}"
    mode: "{{ statsd_folders_mode }}"
  with_items:
    - "{{ statsd_user_home }}"
    - "{{ statsd_config_file | dirname }}"
    - "{{ statsd_log_file | dirname }}"
