---

# Main tasks file for statsd role

- name: 'INIT | Manage variables to use for our target'
  include_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::statsd'
    - 'role::statsd::config'
    - 'role::statsd::init'
    - 'role::statsd::install'


- name: 'INSTALL | Manage os family installation tasks'
  become: 'True'
  include_tasks: "{{ role_path }}/tasks/install_debian.yml"
  tags:
    - 'role::statsd'
    - 'role::statsd::install'


- name: 'INSTALL | Manage Git installation tasks'
  become: 'True'
  include_tasks: "{{ role_path }}/tasks/install_git.yml"
  tags:
    - 'role::statsd'
    - 'role::statsd::install'


- name: 'CONFIG | Manage config tasks'
  become: 'True'
  include_tasks: "{{ role_path }}/tasks/config.yml"
  tags:
    - 'role::statsd'
    - 'role::statsd::config'


- name: 'CONFIG | Manage services tasks'
  become: 'True'
  include_tasks: "{{ role_path }}/tasks/manage_service.yml"
  tags:
    - 'role::statsd'
    - 'role::statsd::config'
    - 'role::statsd::install'
