---

# Tasks about statsd service management

- name: 'SERVICE | STATSD | Manage init.d/systemd statsD service configuration file'
  template:
    src: "{{ role_path }}/templates/{{ ansible_distribution_release }}.j2"
    dest: "{{ statsd_init_dest }}"
    owner: "{{ statsd_init_owner }}"
    group: "{{ statsd_init_group }}"
    mode: "{{ statsd_init_mode }}"
  notify:
    - 'HANDLER | Restart statsd'


# systemD
- name: 'SERVICE | SYSTEMD | Manage notification and log file'
  template:
    src: "{{ role_path }}/templates/{{ item.name }}"
    dest: "{{ item.dest }}"
    owner: 'root'
    group: 'root'
    mode: "{{ item.mode }}"
  with_items:
    - "{{ service_systemd_conf_files }}"
  when: ( ansible_distribution_release != "trusty")
  notify:
    - 'HANDLER | Restart statsd'
