---

# Tasks about statsd service management

- name: 'SERVICE | UPSTART | Manage systemd statsD service configuration file'
  template:
    src: "{{ role_path }}/templates/statsd.service.j2"
    dest: '/etc/systemd/system/statsd.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'check_statsd_service_upstart_managed'
  notify:
    - 'HANDLER | Restart statsd'

- name: 'SERVICE | SYSTEMD | Manage log file'
  template:
    src: "{{ role_path }}/templates/journald.conf.j2"
    dest: '/etc/systemd/journald.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'HANDLER | Restart statsd'
