---

# Handlers main file for statsd role

- name: 'HANDLER | Start statsd'
  systemd:
    name: 'statsd.service'
    state: '{{ statsd_service_state }}'
    enabled: '{{ statsd_service_enabled }}'
  tags:
    - 'role::statsd'
    - 'role::statsd::install'
    - 'role::statsd::config'

- name: 'HANDLER | Restart statsd'
  systemd:
    name: 'statsd.service'
    daemon-reload: 'yes'
    state: 'restarted'
  tags:
    - 'role::statsd'
    - 'role::statsd::install'
    - 'role::statsd::config'
