---

# Handlers main file for statsd role

- name: 'HANDLER | Restart statsd'
  become: True
  service:
    name: "{{ statsd_service.name }}"
    state: 'restarted'
  when: "statsd_service.enabled == 'started'"
  tags:
    - 'role::statsd'
    - 'role::statsd::install'
    - 'role::statsd::config'
