---

# Handlers main file for statsd role

- name: 'HANDLER | Restart statsd'
  become: True
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  with_items: "{{ statsd_service_states }}"
  tags:
    - 'role::statsd'
    - 'role::statsd::install'
    - 'role::statsd::config'
