---
ansible:
  extra_vars:
    ansible_python_interpreter: '/usr/bin/env python2.7'
    no_log: 'False'
    nodejs_version: '4.x'
    nodejs_install_npm_user: 'root'
  raw_env_vars:
    ANSIBLE_NOCOWS: 1
  group_vars:
    all: {}

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint:
  name: 'yamllint'
platforms:
  - name: "statsd-docker-trusty"
    image: 'ubuntu:trusty'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: 'statsd-docker-xenial'
    image: 'solita/ubuntu-systemd:16.04'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: 'statsd-docker-jessie'
    image: 'minimum2scp/systemd-jessie:latest'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: 'statsd-docker-stretch'
    image: 'minimum2scp/systemd-stretch'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
provisioner:
  name: 'ansible'
  lint:
    name: 'ansible-lint'
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  lint:
    name: 'flake8'
